services:
  imu-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        DOCKER_GID: ${DOCKER_GID:-1001}
        DOCKER_UID: ${DOCKER_UID:-1001}
    user: "${DOCKER_UID:-1001}:${DOCKER_GID:-1001}"
    hostname: robotics
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    volumes:
      - ..:/home/dev/imu.rs/
      - /dev/log:/dev/log

