[package]
name = "publisher"
version = "0.1.0"
edition = "2024"
authors = ["Norbert Hańderek <norbert.handerek03@gmail.com>"]

[dependencies]
common = { path = "../common" }
tokio = { version = "1.44.2", features = ["full"] }
rand = "0.9.0"
rand_distr = "0.5.1"